### ISSUE TITLE
All Offline Map

### ISSUE THREAD

**Issue by WawasCode** [WawasCode/adh-app#32]
# Offline Map on a Raspberry Pi — Implementation Checklist

> **Goal**  Deploy a fully‑offline, searchable vector‑tile map (Germany or selected regions) on Raspberry Pi 4/5 boards inside an ad‑hoc network.

---

## A  Build‑time (runs on a laptop / build server)

1. **Region selector script**  
   ⤷ lets operator pick a *country / Bundesland / custom AOI* and produces a `region.conf` with the PBF URL or local path.
2. **Planetiler runner**  
   ⤷ `planetiler <region> --output /tmp/<name>.pmtiles --download`  
   ⤷ outputs `<region>.pmtiles` (vector‑tile archive).
3. **Photon importer**  
   ⤷ clones *komoot/photon* → `photon-import <region>.osm.pbf`  
   ⤷ outputs `photon-<region>/` Lucene index.
4. **Metadata builder**  
   ⤷ generates `manifest.json` with name, bbox, PBF date, zoom range, SHA‑256 checksums & file sizes.
5. **Packager** (zipper)  
   ⤷ bundles `.pmtiles`, `photon‑index/`, `manifest.json` → `<region>.zip` (≈ 150–800 MB).
6. **Integrity checker** *(optional)*  
   ⤷ verifies SHA‑256 before shipping.

---

## B  Pi run‑time infrastructure (Docker‑compose)

| Service | Image (ARM64) | Mounts / Ports | Notes |
|---------|---------------|----------------|-------|
|**go‑pmtiles**|`ghcr.io/protomaps/go-pmtiles`|`./packs/current.pmtiles → /data/current.pmtiles`  <br>Port **8081**|Streams vector tiles + auto‑serves `/style.json`.|
|**Photon**|`ghcr.io/komoot/photon`|`./packs/current-photon → /photon_data`  <br>Port **2322**|Start JVM with `-Xms750m -Xmx1500m`.|
|**Web / SPA**|Your Nginx or Django + Vite image|Port **8000**|Serves React/MapLibre bundle + settings API.|
|**(Opt.) pg_tileserv**|`pramsey/pg_tileserv`|Uses same `db` PostGIS|Only when supporting on‑device AOI imports.|

### Minimal `docker‑compose.pi.yml`
```yaml
version: "3.9"
services:
  tiles:
    image: ghcr.io/protomaps/go-pmtiles:v1.10-arm64
    command: ["serve", "/data/current.pmtiles", "--port", "8081"]
    volumes: ["./packs:/data"]
    ports: ["8081:8081"]

  photon:
    image: ghcr.io/komoot/photon:2025.4.1-arm64
    environment:
      JAVA_TOOL_OPTIONS: "-Xms750m -Xmx1500m"
    volumes: ["./packs/current-photon:/photon_data"]
    ports: ["2322:2322"]

  web:
    build: ./webapp               # React / Vite build
    ports: ["8000:80"]
```

---

## C  “Map‑Manager” subsystem

- **Region list & status** — read `/packs/`, parse each `manifest.json`, show size & date.
- **Upload / import ZIP** — POST, unzip to `/packs/`, verify checksums.  
  *UI*: file‑drop with progress bar.
- **Activate region** — symlink `current.*` → chosen pack, then `docker restart tiles photon`.  
  *UI*: radio button *Use*.
- **Delete region** — remove pack; update list.  
  *UI*: trash‑can icon.
- **Disk usage monitor** — warn if free space < 2 GB.
- **(Opt.) Live AOI import** — upload small AOI PBF → run `osm2pgsql` → serve via `pg_tileserv`.
- **Logs viewer** — tail last 200 lines of each container.

---

## D  Front‑end Map Features (React + MapLibre GL)

1. **GPU vector base‑map** — `style: 'http://pi.local:8081/style.json'`.
2. **Forward geocoding** — `fetch('http://pi.local:2322/api/?q='+encodeURIComponent(txt))`.
3. **Reverse geocoding** — on map click → Photon `/reverse` → popup.
4. **Locate‑me** — browser *Geolocation API*.
5. **Theme switch (day/night)** — swap style JSON or adjust paint rules.
6. **Performance guard** — lower pixel ratio if FPS < 25.
7. **Graceful fallback** — show message if WebGL unavailable.
8. **Attribution modal** — OSM, Planetiler, Photon licenses.
9. **(Opt.) PWA manifest** — “Add to Home Screen”.

---

## E  DevOps & Maintenance

- **CI pipeline** — rebuild packs when Geofabrik posts a new PBF.
- **Version tagging** — `germany‑YYYY‑MM‑DD.zip`; keep last two on Pi.
- **Back‑ups** — nightly `rsync` of `/packs/` to USB SSD.
- **Monitoring** — Grafana/Prometheus or Node‑RED for RAM, disk, container health.
- **Docs** — quick‑start *Build ▸ Copy ▸ Activate* guide for field staff.

---

## Minimal Path to an MVP

1. Build **one** pack (e.g. Bavaria) → steps 1‑5.
2. Deploy services *tiles*, *photon*, *web*.
3. Hard‑code `current.*` symlinks (skip Map‑Manager UI).
4. Implement front‑end items 1‑3.

You now have a fully‑offline, GPU‑rendered map & search running on the Pi.  Iterate from there!

---

## Deliverables Recap

- Build scripts (`build/…`) ✔︎
- Pack format (`<region>.zip`) ✔︎
- Raspberry‑Pi `docker‑compose.yml` ✔︎
- Map‑Manager REST + React settings page ✔︎
- Main MapLibre UI (search + reverse) ✔︎
